### PR TITLE
Cython implementations for to_allele_counts

### PR DESCRIPTION
**Pull request by timothymillar**
Mostly a copy-paste of `genotype_array_count_alleles`.
I'm not completely happy with the handling of GenotypeVectors but this approach seemed cleaner than separate functions.

### CODE REVIEW

**Comment by alimanfoo** [comment]
Hi @timothymillar, so sorry this didn't get any response, my bad.

Out of interest, if you can remember that far back, did you do any benchmarking on this? If so, interested to know what kind of speedup you got.

**Comment by timothymillar** [comment]
No worries @alimanfoo I've re-run some basic benchmarks [here](https://gist.github.com/timothymillar/a4c30666129559a7a56196c13d4e8b25).

- i5-4690S CPU @ 3.20GHz
- anaconda python 3.7.6 with MKL
- ubuntu/18.04.4 

In short, it's a roughly 2x speedup for a trivial case but can be ~10x or more speedup in large/complex cases.

- diploid biallelic shape (3, 2, 2):  2x
- diploid biallelic shape (300000, 100, 2):  5x
- tetraploid multiallelic (8 alleles) shape (300000, 100, 4): 9x

I'm actually having some trouble re-running the unit tests at the moment (pytest refuses to import my code) 
but I think that's to do with python version (as was the case with Travis).

**Comment by alimanfoo** [comment]
Thanks @timothymillar, very nice. The handling of vectors seems fine to me, nice way to avoid too many functions. I pushed a couple of commits to merge in recent changes from master and recythonize and added a release note. If CI passes this seems good to merge to me.

**Comment by timothymillar** [comment]
Sorry I should have picked this up, the handling of dtypes needs to be improved, though I'm a bit confused why it only failed on python 3.8

**Comment by timothymillar** [comment]
@alimanfoo I think the best approach is to use `cnp.int8_t` for the counts and either cast the result to the specified dtype or remove the argument for specifying the dtype

**Comment by alimanfoo** [comment]
Hi @timothymillar 

> I think the best approach is to use `cnp.int8_t` for the counts 

Sounds good.

> ... and either cast the result to the specified dtype or remove the argument for specifying the dtype

I think we could remove the argument for specifying the dtype. If the user wants something else they could always cast the result themselves.

**Comment by alimanfoo** [comment]
> cnp.int8_t

Minor point but we could use `cnp.uint8_t` here, no need to represent negative values.

**Comment by alimanfoo** [comment]
Wonderful, thanks @timothymillar.

**Comment by alimanfoo** [comment]
Included in release v1.3.2 which is up on PyPI, will do conda-forge next week.

**Comment by timothymillar** [comment]
Thanks for you help with this @alimanfoo

**Pull request merged**
